#################
##CINDER services down on Controller 2 & 3
##################
# 

- hosts: controller-serviceverify-2-3
  gather_facts: yes
  remote_user: root
  tags: cinderservicedown
  tasks:


  - name: Cinder services down on Controller 2 and 3
    shell: for i in `cd /etc/init.d/ ; ls cinder-*`; do service $i stop; done
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

##############Run Tempest test for Instance launch  

- hosts: tempest
  gather_facts: yes
  remote_user: root
  tags: interfaceup
  tasks:

  - name: Tempest check
    shell: bash /root/script-volume-tempst.sh
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Verify if tempest is PASSED, press ENTER to continue"


#################
###CINDER services UP on Controller 2 & 3
###################

- hosts: controller-serviceverify-2-3
  gather_facts: yes
  remote_user: root
  tags: cinderserviceup
  tasks:

  - name: Cinder services UP on Controller 2 and 3
    shell: for i in `cd /etc/init.d/ ; ls cinder-*`; do service $i start; done
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Pausing for cinder service to come up on nodes" seconds=1

#################
###Cinder services down on Controller 1 & 3
###################

- hosts: controller-serviceverify-1-3
  gather_facts: yes
  remote_user: root
  tags: cinderservicedown
  tasks:


  - name: Cinder down on Controller 1 and 3
    shell: for i in `cd /etc/init.d/ ; ls cinder-*`; do service $i stop; done
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

##############Run Tempest test for Instance launch

- hosts: tempest
  gather_facts: yes
  remote_user: root
  tags: interfaceup
  tasks:

  - name: Tempest check
    shell: bash /root/script-volume-tempst.sh
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Verify if tempest is PASSED, press ENTER to continue"

#################
####Cinder services UP on Controller 1 & 3
####################

- hosts: controller-serviceverify-1-3
  gather_facts: yes
  remote_user: root
  tags: cinderserviceup
  tasks:

  - name: Cinder services UP on Controller 2 and 3
    shell: for i in `cd /etc/init.d/ ; ls cinder-*`; do service $i start; done
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Pausing for cinder service to come up on nodes" seconds=1

#################
####Cinder services down on Controller 1 & 2
####################


- hosts: controller-serviceverify-1-2
  gather_facts: yes
  remote_user: root
  tags: cinderservicedown
  tasks:


  - name: Cinder down on Controller 1 and 2
    shell: for i in `cd /etc/init.d/ ; ls cinder-*`; do service $i stop; done
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

##############Run Tempest test for Instance launch

- hosts: tempest
  gather_facts: yes
  remote_user: root
  tags: interfaceup
  tasks:

  - name: Tempest check
    shell: bash /root/script-volume-tempst.sh
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Verify if tempest is PASSED, press ENTER to continue"

#################
#####Cinder services UP on Controller 1 & 2
#####################



- hosts: controller-serviceverify-1-2
  gather_facts: yes
  remote_user: root
  tags: cinderserviceup
  tasks:

  - name: Cinder services UP on Controller 1 and 3
    shell: for i in `cd /etc/init.d/ ; ls cinder-*`; do service $i start; done
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Pausing for cinder service to come up on nodes" seconds=1

#####Verify cinder service on all controller nodes

- hosts: controllers-1-2-3
  gather_facts: yes
  remote_user: root
  tags: cinderserviceup
  tasks:

  - name: Verify cinder service on all controller nodes
    shell: for i in `cd /etc/init.d/ ; ls cinder-*`; do service $i status; done
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

