#################
##CINDER services down on Controller 11 & 13
##################
# 

- hosts: controller-serviceverify-11-13
  gather_facts: yes
  remote_user: root
  tags: cinderservicedown
  tasks:


  - name: Cinder services down on Controller 11 and 13
    shell: for i in `cd /etc/init.d/ ; ls cinder-*`; do service $i stop; done
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

##############Run Tempest test for Instance launch  

- hosts: tempest
  gather_facts: yes
  remote_user: root
  tags: interfaceup
  tasks:

  - name: Tempest check
    shell: bash /root/script-volume-tempst.sh
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Verify if tempest is PASSED, press ENTER to continue"


#################
###CINDER services UP on Controller 11 & 13
###################

- hosts: controller-serviceverify-11-13
  gather_facts: yes
  remote_user: root
  tags: cinderserviceup
  tasks:

  - name: Cinder services UP on Controller 11 and 13
    shell: for i in `cd /etc/init.d/ ; ls cinder-*`; do service $i start; done
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Pausing for cinder service to come up on nodes" seconds=10

#################
###Cinder services down on Controller 10 & 13
###################

- hosts: controller-serviceverify-10-13
  gather_facts: yes
  remote_user: root
  tags: cinderservicedown
  tasks:


  - name: Cinder down on Controller 10 and 13
    shell: for i in `cd /etc/init.d/ ; ls cinder-*`; do service $i stop; done
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

##############Run Tempest test for Instance launch

- hosts: tempest
  gather_facts: yes
  remote_user: root
  tags: interfaceup
  tasks:

  - name: Tempest check
    shell: bash /root/script-volume-tempst.sh
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Verify if tempest is PASSED, press ENTER to continue"

#################
####Cinder services UP on Controller 10 & 13
####################

- hosts: controller-serviceverify-10-13
  gather_facts: yes
  remote_user: root
  tags: cinderserviceup
  tasks:

  - name: Cinder services UP on Controller 11 and 13
    shell: for i in `cd /etc/init.d/ ; ls cinder-*`; do service $i start; done
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Pausing for cinder service to come up on nodes" seconds=10

#################
####Cinder services down on Controller 10 & 11
####################


- hosts: controller-serviceverify-10-11
  gather_facts: yes
  remote_user: root
  tags: cinderservicedown
  tasks:


  - name: Cinder down on Controller 10 and 11
    shell: for i in `cd /etc/init.d/ ; ls cinder-*`; do service $i stop; done
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

##############Run Tempest test for Instance launch

- hosts: tempest
  gather_facts: yes
  remote_user: root
  tags: interfaceup
  tasks:

  - name: Tempest check
    shell: bash /root/script-volume-tempst.sh
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Verify if tempest is PASSED, press ENTER to continue"

#################
#####Cinder services UP on Controller 10 & 11
#####################



- hosts: controller-serviceverify-10-11
  gather_facts: yes
  remote_user: root
  tags: cinderserviceup
  tasks:

  - name: Cinder services UP on Controller 10 and 13
    shell: for i in `cd /etc/init.d/ ; ls cinder-*`; do service $i start; done
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Pausing for cinder service to come up on nodes" seconds=10

#####Verify cinder service on all controller nodes

- hosts: controllers-10-11-13
  gather_facts: yes
  remote_user: root
  tags: cinderserviceup
  tasks:

  - name: Verify cinder service on all controller nodes
    shell: for i in `cd /etc/init.d/ ; ls cinder-*`; do service $i status; done
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

