################
#Interface down on node-1
###############

- hosts: controller-1
  gather_facts: yes
  remote_user: root
  tags: interfacedown
  tasks:

  - name: Management interface down on controller node-1
    shell: ifdown bond0.xxxx
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Pausing for interface to go down on node-1" seconds=5

  - name: ETH0 interface down on controller node-1
    shell: ifdown eth0
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Pausing for interface to go down on node-1" seconds=5

#################
##Verify services on Controller 2 & 3
##################
# 

- hosts: controller-serviceverify-2-3
  gather_facts: yes
  remote_user: root
  tags: verifyservices
  tasks:


  - name: verify vip__public
    shell: crm resource status vip__public
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

  - name: verify vip__management
    shell: crm resource status vip__management
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

  - name: verify ping_vip__public
    shell: crm resource status ping_vip__public
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

  - name: verify p_heat-engine
    shell: crm resource status p_heat-engine
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

  - name: verify p_rabbitmq-server
    shell: crm resource status p_rabbitmq-server
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

  - name: verify p_mysql
    shell: crm resource status p_mysql
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

  - name: verify p_heat-engine
    shell: crm resource status p_haproxy
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

  - name: verify crm
    shell: crm status
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Pausing to check crm status on node-2-3"

################
##Interface up on node-1
################
#

- hosts: controller-1
  gather_facts: yes
  remote_user: root
  tags: interfaceup
  tasks:

  - name: Management interface up on controller node-1
    shell: ifup bond0.xxxx
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Pausing for interface to go up on node-1" seconds=5

  - name: Management interface verify on controller node-1
    shell: ifconfig bond0.xxxx
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Pausing for interface verification on node-1"

  - name: ETH0 interface UP on controller node-1
    shell: ifup eth0
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Pausing for interface to go down on node-1" seconds=5


  - name: cororsync service start
    shell: service corosync start
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Pausing for service to come up on node-1" seconds=60

  - name: verify crm
    shell: crm status
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="To check if crm status is OK, enter if it is OK"

################
##Interface down on node-2
################

- hosts: controller-2
  gather_facts: yes
  remote_user: root
  tags: interfacedown
  tasks:

  - name: Management interface down on controller node-2
    shell: ifdown bond0.xxxx
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Pausing for interface to go down on node-2" seconds=5


#################
###Verify services on Controller 1 & 3
###################

- hosts: controller-serviceverify-1-3
  gather_facts: yes
  remote_user: root
  tags: verifyservices
  tasks:


  - name: verify vip__public
    shell: crm resource status vip__public
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

  - name: verify vip__management
    shell: crm resource status vip__management
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

  - name: verify ping_vip__public
    shell: crm resource status ping_vip__public
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

  - name: verify p_heat-engine
    shell: crm resource status p_heat-engine
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

  - name: verify p_rabbitmq-server
    shell: crm resource status p_rabbitmq-server
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

  - name: verify p_mysql
    shell: crm resource status p_mysql
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

  - name: verify p_heat-engine
    shell: crm resource status p_haproxy
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

  - name: verify crm
    shell: crm status
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Pausing to check crm status node-1-3"

################
###Interface up on node-2
#################
##
- hosts: controller-2
  gather_facts: yes
  remote_user: root
  tags: interfaceup
  tasks:

  - name: Management interface up on controller node-2
    shell: ifup bond0.xxxx
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Pausing for interface to go up on node-2" seconds=5

  - name: Management interface verify on controller node-2
    shell: ifup bond0.xxxx
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Pausing for interface verification on node-2"

  - name: cororsync service start
    shell: service corosync start
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Pausing for service to come up" seconds=60

  - name: verify crm
    shell: crm status
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Pausing to check crm status"

################
###Interface down on node-3
#################

- hosts: controller-3
  gather_facts: yes
  remote_user: root
  tags: interfacedown
  tasks:

  - name: Management interface down on controller node-3
    shell: ifdown bond0.xxxx
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Pausing for interface to go down on node-3" seconds=5

#################
####Verify services on Controller 1 & 2
####################

- hosts: controller-serviceverify-1-2
  gather_facts: yes
  remote_user: root
  tags: verifyservices
  tasks:


  - name: verify vip__public
    shell: crm resource status vip__public
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

  - name: verify vip__management
    shell: crm resource status vip__management
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

  - name: verify ping_vip__public
    shell: crm resource status ping_vip__public
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

  - name: verify p_heat-engine
    shell: crm resource status p_heat-engine
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

  - name: verify p_rabbitmq-server
    shell: crm resource status p_rabbitmq-server
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

  - name: verify p_mysql
    shell: crm resource status p_mysql
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

  - name: verify p_heat-engine
    shell: crm resource status p_haproxy
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

  - name: verify crm
    shell: crm status
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Pausing to check crm status on node-1-2"

################
###Interface up on node-3
#################
##
- hosts: controller-3
  gather_facts: yes
  remote_user: root
  tags: interfaceup
  tasks:

  - name: Management interface up on controller node-3
    shell: ifup bond0.xxxx
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Pausing for interface to go up on node-3" seconds=5

  - name: Management interface up on controller node-3
    shell: ifup bond0.xxxx
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Pausing for interface to go up on node-3"

  - name: cororsync service start
    shell: service corosync start
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Pausing for service to come up" seconds=60

  - name: verify crm
    shell: crm status
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Pausing to check crm status on node-3"
#####################
####Tempest check###
#
- hosts: tempest
  gather_facts: yes
  remote_user: root
  tags: interfaceup
  tasks:

  - name: Tempest check
    shell: bash /root/script-tempst.sh
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

