###SAHARA services down on Controller 1

- hosts: controller-1
  gather_facts: yes
  remote_user: root
  tags: saharaservicedown
  tasks:


  - name: SAHARA services down on Controller 1
    service: name=sahara-all state=stopped
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

###SAHARA check

- hosts: tempest
  gather_facts: yes
  remote_user: root
  tags: saharacheck
  tasks:

  - name: sahara check on node-1
    shell: bash /root/test.sh
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Verify if tempest is PASSED, press ENTER to continue"

#####SAHARA services up on Controller 1

- hosts: controller-1
  gather_facts: yes
  remote_user: root
  tags: saharaserviceup
  tasks:

  - name: SAHARA services start on Controller 1
    service: name=sahara-all state=started
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

####SAHARA services down on Controller 2

- hosts: controller-2
  gather_facts: yes
  remote_user: root
  tags: saharaservicedown
  tasks:
  - name: SAHARA services down on Controller 2
    service: name=sahara-all state=stopped
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

####SAHARA check

- hosts: tempest
  gather_facts: yes
  remote_user: root
  tags: saharacheck
  tasks:

  - name: sahara check on node-1
    shell: bash /root/test.sh
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Verify if tempest is PASSED, press ENTER to continue"

######SAHARA services up on Controller 2

- hosts: controller-2
  gather_facts: yes
  remote_user: root
  tags: saharaserviceup
  tasks:

  - name: SAHARA services start on Controller 2
    service: name=sahara-all state=started
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

#######SAHARA services down on Controller 3

- hosts: controller-3
  gather_facts: yes
  remote_user: root
  tags: saharaservicedown
  tasks:

  - name: SAHARA services start on Controller 3
    shell: service sahara-all start
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

######SAHARA check

- hosts: tempest
  gather_facts: yes
  remote_user: root
  tags: saharacheck
  tasks:

  - name: sahara check on node-1
    shell: bash /root/test.sh
    ignore_errors: yes
    register: png
  - debug: var=png.stdout
  - pause: prompt="Verify if tempest is PASSED, press ENTER to continue"

#######SAHARA services up on Controller 3

- hosts: controller-3
  gather_facts: yes
  remote_user: root
  tags: saharaserviceup
  tasks:

  - name: SAHARA services start on Controller 3
    service: name=sahara-all state=started
    ignore_errors: yes
    register: png
  - debug: var=png.stdout

